const CHOOSE_DAY = "CHOOSE_DAY";
const RETRIEVE_SCHEDULE = "RETRIEVE_SCHEDULE";
const RECIEVE_SCHEDULE = "RECIEVE_SCHEDULE";
const CHOOSE_VENUE = "CHOOSE_VENUE";

export default {
	CHOOSE_DAY,
	RETRIEVE_SCHEDULE,
	RECIEVE_SCHEDULE,
	CHOOSE_VENUE
}